name = "tp-autobouffe"
main = "./src/index.ts"
compatibility_date = "2024-03-04"

[triggers]
crons = ["00 7-8 * * 2-6"] # at UTC 7:00-8:00 (Zurich UTC +1 (or UTC +2 summer) to include 9:00) from monday to friday

# secrets
# WEBHOOK_URL = "https://hooks.slack.com/triggers/..."

[vars]
WORKER_ENV = "dev"

[env.prod.vars]
WORKER_ENV = "prod"
